### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Yomguithereal** [Tom-Bonnike/workshop-hetic#1]
https://github.com/Tom-Bonnike/workshop-hetic/blob/master/markov-chain/graph.js#L34

Ta variable devrait probablement s'appeler `weight` plutôt vu que c'est ce qu'elle représente.

https://github.com/Tom-Bonnike/workshop-hetic/blob/master/markov-chain/graph.js#L35

Une meilleure abstraction pour ce genre de chose est possible. Un `MultiSet` ou un `Counter` en python.

https://github.com/Tom-Bonnike/workshop-hetic/blob/master/markov-chain/graph.js#L55

Utilise `node.edges.values()` tu économiseras le destructuring dans ton reduce et tu utiliseras moins de RAM.

**Comment by Tom-Bonnike** [comment]
https://github.com/Tom-Bonnike/workshop-hetic/commit/2e7591a216fbf5f8ffdacd094e1287fb7e1da5f6

C’est vrai que c’est un peu bizarre mon getEdge en Map avec comme valeur la weight et comme clé le node, mais bon.
Et puis… mnemonist is overrated.
